using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Threading.Tasks;
using System.Text.Json;

[ApiController]
[Route("api/[controller]")]
public class MotivacionalController : ControllerBase
{
    private readonly IHttpClientFactory _httpClientFactory;

    public MotivacionalController(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }

    [HttpGet("frase")]
    public IActionResult GetFrase()
    {
        var frases = new[]
        {
            new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },
new { frase = "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello.", autor = "Charles R. Swindoll" },
new { frase = "El único modo de hacer un gran trabajo es amar lo que haces.", autor = "Steve Jobs" },
new { frase = "No cuentes los días, haz que los días cuenten.", autor = "Muhammad Ali" },
new { frase = "Cree que puedes y ya estás a mitad de camino.", autor = "Theodore Roosevelt" },
new { frase = "Nunca es demasiado tarde para ser lo que podrías haber sido.", autor = "George Eliot" },
new { frase = "La felicidad no es algo hecho. Proviene de tus propias acciones.", autor = "Dalai Lama" },
new { frase = "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.", autor = "Steve Jobs" },
new { frase = "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor = "John D. Rockefeller" },
new { frase = "Si puedes soñarlo, puedes lograrlo.", autor = "Walt Disney" },
new { frase = "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor = "Robert Collier" },

        };
        var random = new Random();
        var seleccion = frases[random.Next(frases.Length)];
        return Ok(seleccion);
    }
}